apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-hwy
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-hwy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo-hwy
  template:
    metadata:
      labels:
        app: demo-hwy
    spec:
      containers:
        - name: demo
          image: springboot/demo:0.0.1
          imagePullPolicy: IfNotPresent
          args: ["--spring.config.location=application.properties"]
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: demo-config
              mountPath: /opt/application.properties
              subPath: application.properties
      volumes:
        - name: demo-config
          configMap:
            name: demo-configmap
            items:
              - key: application.properties
                path: application.properties